### ISSUE TITLE
[Feature request] Formula evaluation in belief arguments

### ISSUE THREAD

**Issue by copycat-killer** [jason-lang/jason#14]
It would be useful (and cool) to have a feature like this:

```java
isRaining(true).
goingOut({isRaining(R) & not R}). // result: goingOut(false)
```

```java
// N = 3
+three({N > 2}). // result: three(true)
```

That is, the ability to pass a formula as an argument in a belief. The parser would detect it via bracket delimiters, evaluate, then set the result. Do you think it's viable?

**Comment by rbordini** [comment]
Hi Luke,

This is not in line with the usual knowledge representation in first 
order logic. In Jason we already have a restricted form o 2nd order 
variables because indeed you can write something

goingOut :- isRaining(R) & not R.

in which case R would be instantiated with something that potentially is 
in the belief base and therefore seen as a logical predicate (with a 
true/false value). But in principal parameters to predicates should only 
have terms, that is, things that represent "objects", elements of the 
universe of discourse, not logical formulae. Writing

isRaining(true)

itself is already quite wrong in terms of logical representation. 
Because "isRaining" is a predicate, itself has a true or false value 
depending on whether it appears in the belief base or not, its value 
should NOT be in an argument. Note further there is strong negation, so 
if you have

~isRaining.

in the belief base, that means your agent believes isRaining is false 
(in case closed world assumption is not appropriate in your domain).

cheers

**Comment by copycat-killer** [comment]
So basically I'm just trying to force terms to act like rules, while I should use the latter ones instead.

Indeed, now that I think about it, `isRaining(true)` is really something logically wrong! It should be an atom.

I am surprised at myself, this is some kind of professional deformation.

Thanks for your reply.

**Comment by jomifred** [comment]
> I am surprised at myself, this is some kind of professional deformation.

hehehe, we are all subject to that. Don’t worry.

(and thanks again for all contribution to our project)
