### ISSUE TITLE
Potential Issue with Failure Backtracking?

### ISSUE THREAD

**Issue by MikeVezina** [jason-lang/jason#36]
Hello!

I am relatively new to the Jason / AgentSpeak community, and was wondering if I could get some clarification on an issue that I am having. I've tried to simplify the issue as much as possible, but please let me know if you have any questions about what I've included. I've also gone through the Jason book many times trying to understand why this might be happening, but I've had no luck.

My issue is that when a plan failure itself fails, it doesn't perform any backtracking. Now, I'm not sure if this is intentional behaviour, if I have designed my plan definitions incorrectly, or if this is a potential bug / issue.

I have an example to clarify the situation. The AgentSpeak code that demonstrates the issue is as follows:

![failure_ss_1_code](https://user-images.githubusercontent.com/10552190/66666808-802bb480-ec1f-11e9-885d-64c3459eea8e.png)

The output is as follows:
![failure_ss_1](https://user-images.githubusercontent.com/10552190/66666882-ae10f900-ec1f-11e9-9d43-640b1a78cfc5.png)

What I require clarification on is why -!testFailure does not get considered when -!alwaysFails fails. It actually seems that no failure backtracking is done at all when a plan failure plan (aka -!alwaysFails) fails. In my mind It would be ideal to be able to "catch" this failure through backtracking, but instead I've had to get around this issue by removing the -!alwaysFails definition.

The following code and output is the desired behaviour (although I shouldn't have to omit the -!alwaysFails plan just to get backtracking to work properly).

![failure_ss_expected_code](https://user-images.githubusercontent.com/10552190/66667120-4b6c2d00-ec20-11e9-93ba-1f01bf3b08a5.png)

![failure_ss_expected](https://user-images.githubusercontent.com/10552190/66667129-4f984a80-ec20-11e9-8689-4cdaf906b0cd.png)

If any further clarification is required, don't hesitate to let me know!

Thanks in advance,
Michael

**Comment by rbordini** [comment]
Hi Michael,

This is a really interesting question. Fortunately (or maybe 
unfortunately) it's not a bug, and apologies that the book failed to 
explain this properly. In fact, me made this decision long ago, but we 
agree with you that what you expect is reasonable, so we might 
reconsider and improve the implementation (thanks for the input), just 
let me explain the intuition we had at the time.

The intuition of a "-!g" type of event in the Jason version of 
AgentSpeak is that it is a contingency plan for the plans to achieve 
goal g specifically. Once an instance of such a contingency plans is 
being executed within an intention stack, it is assumed it will handle 
the problem with the attempt to achieve g right below it in the 
intention stack. It may include, for example, moving the world back to a 
"clean" state where the failed goal might be tried again, but then that 
goal needs to be attempted again explicitly, in your example that might 
have looked like:

-!alwaysFails : c1
   <- ...; // do stuff
      !alwaysFails.

-!alwaysFails : c2
   <- ...; // do something else
      !someOtherGoal;
      ...

Now, a -!g plan is used to resolve a problem in attempting to achieve 
"+!g"; you specify those plans because in principle you know how to able 
handle failures of g, and it's OK to try other things that might 
themselves fail, but you should be careful enough for the contingency 
plan itself not to fail. If that contingency plan of yours fails before 
it even attempted anything else, it seems you are so "lost", or in such 
a "mess", that there is no hope to achieve that intention anymore, so 
the whole stack gets deleted (which is the error message you see there). 
For sure we wouldn't want the plans for -!g to be recursively attempted.

If, instead, you don't specify contingency plans at all for a goal g1, 
that means the agent cannot cope with such failures. So if a plan for g1 
then fails and achieving it was needed for the agent to achieve g2, then 
g2 is also failing. That's why when you omit the contingency plan, 
things work as you expected.

However, as said above, there is certainly a point in treating a failure 
in the contingency plan as a failure in the original goal. We will 
reconsider this but even if we decide to change it will take sometime 
before the Jason implementation is improved. At least there should be 
ways around this problem to produce what you are trying to in the 
current version of Jason. If you need help in doing so please let us know.

Best,

Rafael Bordini and Jomi Hubner

**Comment by MikeVezina** [comment]
Hey Rafael,

Thank you for the prompt and detailed explanation. I understand and follow your logic for why this is the case, thank you for taking the time to explain everything! I have a few good ideas as to how I can get around this.

In the meantime, I was wondering if it is possible to include this special case on the FAQ webpage just so the information is available to anyone else that may be encountering the issue. As an alternative, a bit more detail in the error message could be helpful (maybe something along the lines of "could not finish intention (backtracking will not take place)"). 

Let me know what you think of this, and again thank you for your help!

Michael

**Comment by rbordini** [comment]
Hi Michael,

Certainly a good idea to put in the FAQ!  Changing this to throw a 
specific error would take a bit more time, but we'll certainly update 
the FAQ in due time.

Thanks again for helping us improve Jason!

Cheers,

Rafael

**Comment by jomifred** [comment]
Hi Michael,

thanks again for your suggestion. We discussed the issue  and decided to include the failure cascading feature as you suggest. The GitHub version of Jason includes this implementation and it will be available in Jason 2.5.

Thanks

Jomi

**Comment by rbordini** [comment]
Hi Michael,

In fact, Jomi developed a slightly different proposal than I think you 
had in mind, that we had already discussed a few years ago (it was in 
our todo  list, we found). When a contingency plan fails, it's kept on 
the stack and we search down the stack to see if any goals below it in 
the scan has contingency plans and we generate an event for the failure 
of that goal. This means that the agent can reason about the fact that a 
contingency plan for a subgoal was already tried and failed (of course 
this is not so easy to do, but at least it's possible).

Again, thanks for supporting Jason!

Cheers,

Rafael
